name: Load test

on: [workflow_dispatch]

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  contents: read  # This is required for actions/checkout

env:
  # For AZURE_WEBAPP_NAME enter just the name, not the full URL.
  RESOURCE_GROUP: az2006-rg
  LOAD_TEST_RESOURCE: az2006loadtest
  AZURE_WEBAPP_NAME: az2006app50770167 

jobs:
  # This workflow consists of a single job called "loadtest"

  loadtest:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      #Login in your azure subscription using OpenID Connect (credentials stored as GitHub secrets in repo)
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Run the load test
      - name: Azure Load Testing
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: 'config.yaml'
          loadTestResource: ${{ env.LOAD_TEST_RESOURCE}}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          env: |
            [
              {
              "name": "webapp",
              "value": "${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
              }
            ]

      # upload the published website code artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: loadTestResults
          path: ${{github.workspace}}/loadTest

          
