name: Load test

on: [workflow_dispatch]

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  contents: read  # This is required for actions/checkout

env:
  RESOURCE_GROUP: az2006-rg
  LOAD_TEST_RESOURCE: az2006loadtest
  AZURE_WEBAPP_NAME: az2006app50770167 

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install missing dependencies
      - name: Install dependencies
        run: npm install @actions/core

      # Login to your Azure subscription using OpenID Connect
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Load Test via CLI
        run: |
          az load test create --resource-group $RESOURCE_GROUP --load-test-resource $LOAD_TEST_RESOURCE --test-config-file config.yaml
        env:
          AZURE_WEBAPP_NAME: ${{ env.AZURE_WEBAPP_NAME }}
          RESOURCE_GROUP: ${{ env.RESOURCE_GROUP }}
          LOAD_TEST_RESOURCE: ${{ env.LOAD_TEST_RESOURCE }}

      # # Run the load test
      # - name: Azure Load Testing
      #   uses: azure/load-testing@v1
      #   with:
      #     loadTestConfigFile: 'config.yaml'
      #     loadTestResource: ${{ env.LOAD_TEST_RESOURCE }}
      #     resourceGroup: ${{ env.RESOURCE_GROUP }}
      #     env: |
      #       [
      #         {
      #         "name": "webapp",
      #         "value": "${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
      #         }
      #       ]

      # Upload the published website code artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: loadTestResults
          path: ${{ github.workspace }}/loadTest
